<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\config_quoteandsell;

class config_quoteandsellSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
        [
            'name_field_1'              => '', 
            'enable_field_1'            => '0', 
            'name_field_2'              => '', 
            'enable_field_2'            => '0', 
            'name_field_3'              => '', 
            'enable_field_3'            => '0', 
            'name_field_4'              => '', 
            'enable_field_4'            => '0', 
            'name_field_5'              => '', 
            'enable_field_5'            => '0', 
            'name_category_1'           => 'Lineas de Productos',
            'enable_category_1'         => '1',
            'name_category_2'           => '',
            'enable_category_2'         => '0',
            'name_category_3'           => '',
            'enable_category_3'         => '0',
            'name_category_4'           => '',
            'enable_category_4'         => '0',
            'name_category_5'           => '',
            'enable_category_5'         => '0',
            'company_name'              => 'Corporación Lanco',
            'company_rif'               => 'J410252871',
            'company_address'           => 'Avenida Giffoni con Avenida Cementerio, Centro Commercial Gil-Rob, Galpón Nro. 6, Zona Industrial III, Barquisimeto, Edo. Lara',
            'company_contact_email'     => 'atcliente@corporacionlanco.com',
            'company_notification_email'=> 'tienda.autogama@gmail.com',
            'company_contact_phone'     => '(+58) 0251-2692015 / 0251-2691888',
            'company_logo'              => '',
            'company_facebook'          => '',
            'company_instagram'         => '@CORPORACIONLANCO',
            'company_twitter'           => '',
            'company_whatsapp'          => '',
            'company_contact_name_1'    => 'Argenis Polanco - Gerencia',
            'company_contact_email_1'   => 'argenisjpolanco@gmail.com',
            'company_contact_movil_1'   => '4245079262',
            'company_contact_1_enable'  => '1',
            'company_contact_name_2'    => '',
            'company_contact_email_2'   => '',
            'company_contact_movil_2'   => '',
            'company_contact_2_enable'  => '0',
            'company_contact_name_3'    => '',
            'company_contact_email_3'   => '',
            'company_contact_movil_3'   => '',
            'company_contact_3_enable'  => '0',
            'company_contact_qs_name_1'         => '',
            'company_contact_qs_email_1'        => '',
            'company_contact_qs_movil_1'        => '',
            'company_contact_qs_1_enable'       => '0',
            'company_contact_qs_name_2'         => '',
            'company_contact_qs_email_2'        => '',
            'company_contact_qs_movil_2'        => '',
            'company_contact_qs_1_enable'       => '0',
            'company_contact_pay_name_1'        => '',
            'company_contact_pay_email_1'       => '',
            'company_contact_pay_movil_1'       => '',
            'company_contact_pay_1_enable'      => '0',
            'company_contact_pay_name_2'        => '',
            'company_contact_pay_email_2'       => '',
            'company_contact_pay_movil_2'       => '',
            'company_contact_pay_1_enable'      => '0',
            'company_contact_movaut_name_1'     => '',
            'company_contact_movaut_email_1'    => '',
            'company_contact_movaut_movil_1'    => '',
            'company_contact_movaut_1_enable'   => '0',
            'company_contact_movaut_name_2'     => '',
            'company_contact_movaut_email_2'    => '',
            'company_contact_movaut_movil_2'    => '',
            'company_contact_movaut_1_enable'   => '0',
            'company_contact_movcpt_name_1'     => '',
            'company_contact_movcpt_email_1'    => '',
            'company_contact_movcpt_movil_1'    => '',
            'company_contact_movcpt_1_enable'   => '0',
            'company_contact_movcpt_name_2'     => '',
            'company_contact_movcpt_email_2'    => '',
            'company_contact_movcpt_movil_2'    => '',
            'company_contact_movcpt_1_enable'   => '0',
            'company_contact_movshp_name_1'     => '',
            'company_contact_movshp_email_1'    => '',
            'company_contact_movshp_movil_1'    => '',
            'company_contact_movshp_1_enable'   => '0',
            'company_contact_movshp_name_2'     => '',
            'company_contact_movshp_email_2'    => '',
            'company_contact_movshp_movil_2'    => '',
            'company_contact_movshp_1_enable'   => '0',
            'company_namecount_bank_1'  => '',
            'company_namecount_bank_2'  => '',
            'company_namecount_bank_3'  => '',
            'Image_slider_1'            => '',
            'Image_slider_2'            => '',
            'Image_slider_3'            => '',
            'Image_slider_4'            => '',
            'Image_slider_5'            => '',
           
            'store_box1_title'          => '',
            'store_box1_Body'           => '',
            'store_box1_footer'         => '',
            'store_box1_image'          => '',
            'store_box1_image_Place'    => 'Top',
            'store_box1_active'         => '1',
           
            'store_box2_title'          => '',
            'store_box2_Body'           => '',
            'store_box2_footer'         => '',
            'store_box2_image'          => '',
            'store_box2_image_place'    => 'Top',
            'store_box2_active'         => '1',
           
            'store_box3_title'          => '',
            'store_box3_Body'           => '',
            'store_box3_footer'         => '',
            'store_box3_image'          => '',
            'store_box3_image_place'    => 'Top',
            'store_box3_active'         => '1',
           
            'store_box4_title'          => '',
            'store_box4_Body'           => '',
            'store_box4_footer'         => '',
            'store_box4_image'          => '',
            'store_box4_image_place'    => 'Top',
            'store_box4_active'         => '0',
           
            'store_box5_title'          => '',
            'store_box5_Body'           => '',
            'store_box5_footer'         => '',
            'store_box5_image'          => '',
            'store_box5_image_place'    => 'Top',
            'store_box5_active'         => '0',

            'section_sales_active'      => '0',
            'product_catagory_sales'    => '',
            'Imagen_sales'              => '',
            'text_sales'                => '',
            'flash_message'             => '',
            'Date_begin_Flash'          => '',
            'Date_end_Flash'            => '',
            'flash_banner'              => '',
            'Date_begin_banner'         => '',
            'Date_end_banner'           => '',
            'text_notification_email'   => '',
            'text_notification_sms'     => '',
            'view_type_Products'        => 'Pinterest-sm',
            'view_type_scream'          => 'ByCategory',
            'Show_price_user_logout'    => '1',
            'modeFunction'              => 'quoteandsell',
            'TypeStore'                 => 'autoparts',
            'Confirmate_Sell_First_Pay' => '1',
            'api_sms_key'               => 'de1b8f07-eb5d-43db-9206-506d852c804e',
            'Icon_typestore'            => 'fa fa-shopping-cart',
            'Button_modeFunction'       => 'Comprar',
            'Label_modeFunction'        => 'Compra',
            'product_typestore'         => 'Lubricantes y Refrigerantes para Vehículos', 
            'Active_site'               => '1',   
            'Active_store'              => '1',  
            'Category_id'               => '1',  
            'ModoDemo'                  => '0',
            'TypeDemo'                  => '0',                      
            'Information_footer'        => 'Corporación Lanco',
            'Tutorial_site'             => ''
                                            
        ],
    );    
    config_quoteandsell::insert($data);
    
    }
}
